name: Carrier Owl

on:
  schedule:
    # github actions のデフォルトの time zone が UTC なので、日本時間 - 9時間 した値を書く
    - cron:  '50 0 * * 0,3,4,5,6'
  workflow_dispatch:
  
  push:
    branches:
      - test-send-to-slack

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.10.4

      - name: Run image
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.7.0

      - name: install dependencies
        run: poetry install

      - name: Run owl
        run:
          poetry run python src/carrier_owl.py
        env:
          SLACK_ID: ${{ secrets.SLACK_ID }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}


